package com.nathaniel.motus.cavevin.ui.theme

import androidx.compose.ui.graphics.Color

val brown700= Color(0xff5d4037)
val brown900=Color(0xff3e2723)
val brown400=Color(0xff8d6e63)
val pureWhite=Color(0xffffffff)
val pureBlack=Color(0xff000000)
val green900=Color(0xff1b5e20)
val greenCustomDark=Color(0xff003300)
val redWineColor=Color(0xffba000d)
val whiteWhineColor=Color(0xfffbc02d)
val pinkWineColor=Color(0xffe040fb)

val md_theme_light_primary = Color(0xFF9B4427)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onPrimaryContainer = Color(0xFF3A0B00)
val md_theme_light_secondary = Color(0xFF77574D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onSecondaryContainer = Color(0xFF2C160E)
val md_theme_light_tertiary = Color(0xFF6B5E2F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF4E2A7)
val md_theme_light_onTertiaryContainer = Color(0xFF221B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFF5DED7)
val md_theme_light_onSurfaceVariant = Color(0xFF53433F)
val md_theme_light_outline = Color(0xFF85736E)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
val md_theme_light_inverseSurface = Color(0xFF362F2D)
val md_theme_light_inversePrimary = Color(0xFFFFB59E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF9B4427)
val md_theme_light_outlineVariant = Color(0xFFD8C2BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB59E)
val md_theme_dark_onPrimary = Color(0xFF5D1800)
val md_theme_dark_primaryContainer = Color(0xFF7C2D12)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_secondary = Color(0xFFE7BDB1)
val md_theme_dark_onSecondary = Color(0xFF442A22)
val md_theme_dark_secondaryContainer = Color(0xFF5D4037)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_tertiary = Color(0xFFD7C68D)
val md_theme_dark_onTertiary = Color(0xFF3A3005)
val md_theme_dark_tertiaryContainer = Color(0xFF52461A)
val md_theme_dark_onTertiaryContainer = Color(0xFFF4E2A7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DC)
val md_theme_dark_surfaceVariant = Color(0xFF53433F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BC)
val md_theme_dark_outline = Color(0xFFA08D87)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFF9B4427)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB59E)
val md_theme_dark_outlineVariant = Color(0xFF53433F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF5D4037)